-- ---------------------------------------------------------------------
-- Startkatalog (Konzept 4.3 und 5.2)
-- ---------------------------------------------------------------------
--
-- ERZEUGT — nicht von Hand aendern.
-- Quelle: supabase/seed/catalog.json
-- Neu erzeugen: node scripts/build-catalog-migration.mjs
--
-- 27 Kategorien, 273 Produkte,
-- 46 Kategorie- und 273 Produktregeln.
--
-- Der Katalog macht den Normalfall beim Erfassen zum Einzeiler: Wer "Vollmilch"
-- tippt, bekommt Lagerort und Haltbarkeit vorgeschlagen und muss kein Datum
-- suchen. Die Werte sind bewusst konservativ — eine zu fruehe Warnung ist
-- harmlos, eine zu spaete bedeutet verdorbene Ware.
--
-- Wiederholt ausfuehrbar: Kategorien und Produkte werden bei Konflikt
-- aktualisiert, die Regeln des Startkatalogs vorher weggeraeumt. Gelernte
-- Regeln (source='learned') und KI-Schaetzungen (source='ai') bleiben stehen —
-- sie sind an source und household_id erkennbar.
-- ---------------------------------------------------------------------

-- 1. Kategorien --------------------------------------------------------

insert into public.categories (slug, name, sort_order) values
  ('fresh-fruit', 'Frischobst', 10),
  ('fresh-vegetables', 'Frischgemüse', 20),
  ('salad-herbs', 'Salat & frische Kräuter', 30),
  ('potatoes-root-vegetables', 'Kartoffeln, Zwiebeln & Lagergemüse', 40),
  ('milk-cream', 'Milch & Rahm', 50),
  ('yogurt-quark', 'Joghurt & Quark', 60),
  ('hard-cheese', 'Hart- & Halbhartkäse', 70),
  ('soft-cheese', 'Weich- & Frischkäse', 80),
  ('butter-fats', 'Butter & Streichfette', 90),
  ('eggs', 'Eier', 100),
  ('fresh-meat', 'Frischfleisch, Poulet & Hackfleisch', 110),
  ('sausages-cold-cuts', 'Wurstwaren & Aufschnitt', 120),
  ('fish-seafood', 'Fisch & Meeresfrüchte', 130),
  ('chilled-convenience', 'Kühlfrische Fertigprodukte & Fleischalternativen', 140),
  ('frozen-food', 'Tiefkühlprodukte', 150),
  ('bread-bakery', 'Brot & Backwaren', 160),
  ('pasta-rice-cereals', 'Teigwaren, Reis & Müesli', 170),
  ('flour-baking', 'Mehl, Zucker & Backzutaten', 180),
  ('canned-jarred', 'Konserven & Gläser', 190),
  ('sauces-condiments', 'Saucen, Senf & Mayonnaise', 200),
  ('oils-vinegar', 'Öle & Essig', 210),
  ('spices-broth', 'Gewürze, Bouillon & Trockensuppen', 220),
  ('sweet-spreads', 'Konfitüre, Honig & süsse Aufstriche', 230),
  ('sweets-snacks', 'Süsswaren, Snacks & Nüsse', 240),
  ('coffee-tea', 'Kaffee & Tee', 250),
  ('beverages', 'Getränke', 260),
  ('other', 'Sonstiges', 999)
on conflict (slug) do update
  set name       = excluded.name,
      sort_order = excluded.sort_order,
      updated_at = now();

-- 2. Produkte ----------------------------------------------------------
-- Global, also household_id = null. Deshalb source='seed' und nicht 'user';
-- der CHECK products_scope_matches_source erzwingt diesen Zusammenhang.

insert into public.products
  (name, normalized_name, category_id, default_unit, default_storage,
   source, verified, household_id)
select v.name, v.normalized_name, c.id, v.default_unit, v.default_storage,
       'seed', true, null
from (values
  ('Apfelsaft', 'apfelsaft', 'beverages', 'ml', 'pantry'),
  ('Bier', 'bier', 'beverages', 'ml', 'pantry'),
  ('Cola', 'cola', 'beverages', 'ml', 'pantry'),
  ('Eistee', 'eistee', 'beverages', 'ml', 'pantry'),
  ('Mineralwasser mit Kohlensäure', 'mineralwasser mit kohlensaeure', 'beverages', 'ml', 'pantry'),
  ('Mineralwasser ohne Kohlensäure', 'mineralwasser ohne kohlensaeure', 'beverages', 'ml', 'pantry'),
  ('Orangensaft', 'orangensaft', 'beverages', 'ml', 'pantry'),
  ('Rotwein', 'rotwein', 'beverages', 'ml', 'pantry'),
  ('Sirup', 'sirup', 'beverages', 'ml', 'pantry'),
  ('Weisswein', 'weisswein', 'beverages', 'ml', 'pantry'),
  ('Baguette', 'baguette', 'bread-bakery', 'piece', 'pantry'),
  ('Bauernbrot', 'bauernbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Bürli', 'buerli', 'bread-bakery', 'piece', 'pantry'),
  ('Burgerbrötchen', 'burgerbroetchen', 'bread-bakery', 'piece', 'pantry'),
  ('Ciabatta', 'ciabatta', 'bread-bakery', 'piece', 'pantry'),
  ('Dinkelbrot', 'dinkelbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Fladenbrot', 'fladenbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Gipfeli', 'gipfeli', 'bread-bakery', 'piece', 'pantry'),
  ('Halbweissbrot', 'halbweissbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Knäckebrot', 'knaeckebrot', 'bread-bakery', 'piece', 'pantry'),
  ('Laugenbrezel', 'laugenbrezel', 'bread-bakery', 'piece', 'pantry'),
  ('Marmorcake', 'marmorcake', 'bread-bakery', 'piece', 'pantry'),
  ('Muffin', 'muffin', 'bread-bakery', 'piece', 'pantry'),
  ('Nussgipfel', 'nussgipfel', 'bread-bakery', 'piece', 'pantry'),
  ('Pitabrot', 'pitabrot', 'bread-bakery', 'piece', 'pantry'),
  ('Ruchbrot', 'ruchbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Sauerteigbrot', 'sauerteigbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Toastbrot', 'toastbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Tortilla Wraps', 'tortilla wraps', 'bread-bakery', 'piece', 'pantry'),
  ('Vollkornbrot', 'vollkornbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Vollkorntoastbrot', 'vollkorntoastbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Weggli', 'weggli', 'bread-bakery', 'piece', 'pantry'),
  ('Weissbrot', 'weissbrot', 'bread-bakery', 'piece', 'pantry'),
  ('Zopf', 'zopf zoepfe', 'bread-bakery', 'piece', 'pantry'),
  ('Zwieback', 'zwieback', 'bread-bakery', 'piece', 'pantry'),
  ('Bratbutter', 'bratbutter', 'butter-fats', 'g', 'fridge'),
  ('Butter', 'butter', 'butter-fats', 'g', 'fridge'),
  ('Margarine', 'margarine', 'butter-fats', 'g', 'fridge'),
  ('Streichbutter', 'streichbutter', 'butter-fats', 'g', 'fridge'),
  ('Essiggurken', 'essiggurken', 'canned-jarred', 'g', 'pantry'),
  ('Kichererbsen', 'kichererbsen', 'canned-jarred', 'g', 'pantry'),
  ('Kidneybohnen', 'kidneybohnen', 'canned-jarred', 'g', 'pantry'),
  ('Mais aus der Dose', 'mais aus der dose', 'canned-jarred', 'g', 'pantry'),
  ('Pelati', 'pelati', 'canned-jarred', 'g', 'pantry'),
  ('Thon in der Dose', 'thon in der dose', 'canned-jarred', 'g', 'pantry'),
  ('Tomatenpüree', 'tomatenpueree', 'canned-jarred', 'g', 'pantry'),
  ('Falafel', 'falafel', 'chilled-convenience', 'piece', 'fridge'),
  ('Guacamole', 'guacamole', 'chilled-convenience', 'piece', 'fridge'),
  ('Hummus', 'hummus', 'chilled-convenience', 'piece', 'fridge'),
  ('Kuchenteig', 'kuchenteig', 'chilled-convenience', 'piece', 'fridge'),
  ('Pflanzliches Hackfleisch', 'pflanzliches hackfleisch', 'chilled-convenience', 'g', 'fridge'),
  ('Pizzateig', 'pizzateig', 'chilled-convenience', 'piece', 'fridge'),
  ('Räuchertofu', 'raeuchertofu', 'chilled-convenience', 'piece', 'fridge'),
  ('Rauchtofu', 'rauchtofu', 'chilled-convenience', 'g', 'fridge'),
  ('Tofu', 'tofu', 'chilled-convenience', 'piece', 'fridge'),
  ('Tofu natur', 'tofu natur', 'chilled-convenience', 'g', 'fridge'),
  ('Veganes Geschnetzeltes', 'veganes geschnetzeltes', 'chilled-convenience', 'g', 'fridge'),
  ('Vegi-Bratwurst', 'vegi bratwurst', 'chilled-convenience', 'piece', 'fridge'),
  ('Vegi-Burger', 'vegi burger', 'chilled-convenience', 'piece', 'fridge'),
  ('Gemahlener Kaffee', 'gemahlener kaffee', 'coffee-tea', 'g', 'pantry'),
  ('Kaffeebohnen', 'kaffeebohnen', 'coffee-tea', 'g', 'pantry'),
  ('Kaffeekapseln', 'kaffeekapseln', 'coffee-tea', 'piece', 'pantry'),
  ('Kräutertee', 'kraeutertee', 'coffee-tea', 'piece', 'pantry'),
  ('Schwarztee', 'schwarztee', 'coffee-tea', 'piece', 'pantry'),
  ('Eier', 'eier', 'eggs', 'piece', 'fridge'),
  ('Gekochte Eier', 'gekochte eier', 'eggs', 'piece', 'fridge'),
  ('Crevetten', 'crevetten', 'fish-seafood', 'g', 'fridge'),
  ('Eglifilet', 'eglifilet', 'fish-seafood', 'g', 'fridge'),
  ('Forellenfilet', 'forellenfilet', 'fish-seafood', 'g', 'fridge'),
  ('Kabeljaufilet', 'kabeljaufilet', 'fish-seafood', 'g', 'fridge'),
  ('Lachsfilet', 'lachsfilet', 'fish-seafood', 'g', 'fridge'),
  ('Miesmuscheln', 'miesmuscheln', 'fish-seafood', 'g', 'fridge'),
  ('Räucherlachs', 'raeucherlachs', 'fish-seafood', 'g', 'fridge'),
  ('Surimi', 'surimi', 'fish-seafood', 'g', 'fridge'),
  ('Backpulver', 'backpulver', 'flour-baking', 'g', 'pantry'),
  ('Blätterteig', 'blaetterteig', 'flour-baking', 'piece', 'fridge'),
  ('Frischhefe', 'frischhefe', 'flour-baking', 'g', 'fridge'),
  ('Gemahlene Haselnüsse', 'gemahlene haselnuesse', 'flour-baking', 'g', 'pantry'),
  ('Kakaopulver', 'kakaopulver', 'flour-baking', 'g', 'pantry'),
  ('Maisstärke', 'maisstaerke', 'flour-baking', 'g', 'pantry'),
  ('Puderzucker', 'puderzucker', 'flour-baking', 'g', 'pantry'),
  ('Rosinen', 'rosinen', 'flour-baking', 'g', 'pantry'),
  ('Ruchmehl', 'ruchmehl', 'flour-baking', 'g', 'pantry'),
  ('Trockenhefe', 'trockenhefe', 'flour-baking', 'g', 'pantry'),
  ('Vanillezucker', 'vanillezucker', 'flour-baking', 'g', 'pantry'),
  ('Weissmehl', 'weissmehl', 'flour-baking', 'g', 'pantry'),
  ('Zopfmehl', 'zopfmehl', 'flour-baking', 'g', 'pantry'),
  ('Zucker', 'zucker', 'flour-baking', 'g', 'pantry'),
  ('Ananas', 'ananas', 'fresh-fruit', 'piece', 'pantry'),
  ('Apfel', 'apfel aepfel', 'fresh-fruit', 'piece', 'pantry'),
  ('Aprikosen', 'aprikosen', 'fresh-fruit', 'g', 'fridge'),
  ('Avocado', 'avocado', 'fresh-fruit', 'piece', 'pantry'),
  ('Banane', 'banane', 'fresh-fruit', 'piece', 'pantry'),
  ('Birne', 'birne', 'fresh-fruit', 'piece', 'pantry'),
  ('Brombeeren', 'brombeeren', 'fresh-fruit', 'g', 'fridge'),
  ('Erdbeeren', 'erdbeeren', 'fresh-fruit', 'g', 'fridge'),
  ('Heidelbeeren', 'heidelbeeren', 'fresh-fruit', 'g', 'fridge'),
  ('Himbeeren', 'himbeeren', 'fresh-fruit', 'g', 'fridge'),
  ('Honigmelone', 'honigmelone', 'fresh-fruit', 'piece', 'fridge'),
  ('Kiwi', 'kiwi', 'fresh-fruit', 'piece', 'pantry'),
  ('Mandarine', 'mandarine', 'fresh-fruit', 'piece', 'pantry'),
  ('Nektarine', 'nektarine', 'fresh-fruit', 'piece', 'fridge'),
  ('Orange', 'orange', 'fresh-fruit', 'piece', 'pantry'),
  ('Pfirsich', 'pfirsich', 'fresh-fruit', 'piece', 'fridge'),
  ('Wassermelone', 'wassermelone', 'fresh-fruit', 'piece', 'fridge'),
  ('Weintrauben', 'weintrauben', 'fresh-fruit', 'g', 'fridge'),
  ('Zitrone', 'zitrone', 'fresh-fruit', 'piece', 'pantry'),
  ('Zwetschgen', 'zwetschgen', 'fresh-fruit', 'g', 'fridge'),
  ('Entrecôte', 'entrecote', 'fresh-meat', 'g', 'fridge'),
  ('Ganzes Poulet', 'ganzes poulet', 'fresh-meat', 'piece', 'fridge'),
  ('Hackfleisch gemischt', 'hackfleisch gemischt', 'fresh-meat', 'g', 'fridge'),
  ('Hacktätschli', 'hacktaetschli', 'fresh-meat', 'piece', 'fridge'),
  ('Kalbsschnitzel', 'kalbsschnitzel', 'fresh-meat', 'g', 'fridge'),
  ('Lammkoteletts', 'lammkoteletts', 'fresh-meat', 'g', 'fridge'),
  ('Poulet-Geschnetzeltes', 'poulet geschnetzeltes', 'fresh-meat', 'g', 'fridge'),
  ('Pouletbrust', 'pouletbrust', 'fresh-meat', 'g', 'fridge'),
  ('Pouletschenkel', 'pouletschenkel', 'fresh-meat', 'g', 'fridge'),
  ('Rindsfilet', 'rindsfilet', 'fresh-meat', 'g', 'fridge'),
  ('Rindshackfleisch', 'rindshackfleisch', 'fresh-meat', 'g', 'fridge'),
  ('Rindsplätzli', 'rindsplaetzli', 'fresh-meat', 'g', 'fridge'),
  ('Rindsvoressen', 'rindsvoressen', 'fresh-meat', 'g', 'fridge'),
  ('Schweinsfilet', 'schweinsfilet', 'fresh-meat', 'g', 'fridge'),
  ('Schweinskotelett', 'schweinskotelett', 'fresh-meat', 'g', 'fridge'),
  ('Schweinsschnitzel', 'schweinsschnitzel', 'fresh-meat', 'g', 'fridge'),
  ('Trutenbrust', 'trutenbrust', 'fresh-meat', 'g', 'fridge'),
  ('Aubergine', 'aubergine', 'fresh-vegetables', 'piece', 'fridge'),
  ('Blumenkohl', 'blumenkohl', 'fresh-vegetables', 'piece', 'fridge'),
  ('Broccoli', 'broccoli', 'fresh-vegetables', 'piece', 'fridge'),
  ('Champignons', 'champignons', 'fresh-vegetables', 'g', 'fridge'),
  ('Cherrytomaten', 'cherrytomaten', 'fresh-vegetables', 'g', 'pantry'),
  ('Fenchel', 'fenchel', 'fresh-vegetables', 'piece', 'fridge'),
  ('Frühlingszwiebeln', 'fruehlingszwiebeln', 'fresh-vegetables', 'piece', 'fridge'),
  ('Grüne Bohnen', 'gruene bohnen', 'fresh-vegetables', 'g', 'fridge'),
  ('Gurke', 'gurke', 'fresh-vegetables', 'piece', 'fridge'),
  ('Kohlrabi', 'kohlrabi', 'fresh-vegetables', 'piece', 'fridge'),
  ('Lauch', 'lauch', 'fresh-vegetables', 'piece', 'fridge'),
  ('Peperoni', 'peperoni', 'fresh-vegetables', 'piece', 'fridge'),
  ('Spinat', 'spinat', 'fresh-vegetables', 'g', 'fridge'),
  ('Stangensellerie', 'stangensellerie', 'fresh-vegetables', 'piece', 'fridge'),
  ('Tomaten', 'tomaten', 'fresh-vegetables', 'g', 'pantry'),
  ('Zucchetti', 'zucchetti', 'fresh-vegetables', 'piece', 'fridge'),
  ('Chicken Nuggets', 'chicken nuggets', 'frozen-food', 'g', 'freezer'),
  ('Fischstäbchen', 'fischstaebchen', 'frozen-food', 'piece', 'freezer'),
  ('Glace', 'glace', 'frozen-food', 'ml', 'freezer'),
  ('Pommes frites', 'pommes frites', 'frozen-food', 'g', 'freezer'),
  ('Tiefkühl-Gipfeli', 'tiefkuehl gipfeli', 'frozen-food', 'piece', 'freezer'),
  ('Tiefkühlbeeren', 'tiefkuehlbeeren', 'frozen-food', 'g', 'freezer'),
  ('Tiefkühlerbsen', 'tiefkuehlerbsen', 'frozen-food', 'g', 'freezer'),
  ('Tiefkühlgemüse-Mischung', 'tiefkuehlgemuese mischung', 'frozen-food', 'g', 'freezer'),
  ('Tiefkühllasagne', 'tiefkuehllasagne', 'frozen-food', 'piece', 'freezer'),
  ('Tiefkühlpizza', 'tiefkuehlpizza', 'frozen-food', 'piece', 'freezer'),
  ('Tiefkühlspinat', 'tiefkuehlspinat', 'frozen-food', 'g', 'freezer'),
  ('Appenzeller', 'appenzeller', 'hard-cheese', 'g', 'fridge'),
  ('Emmentaler', 'emmentaler', 'hard-cheese', 'g', 'fridge'),
  ('Fondue-Mischung', 'fondue mischung', 'hard-cheese', 'g', 'fridge'),
  ('Gruyère', 'gruyere', 'hard-cheese', 'g', 'fridge'),
  ('Käsescheiben', 'kaesescheiben', 'hard-cheese', 'g', 'fridge'),
  ('Parmesan', 'parmesan', 'hard-cheese', 'g', 'fridge'),
  ('Raclettekäse', 'raclettekaese', 'hard-cheese', 'g', 'fridge'),
  ('Reibkäse', 'reibkaese', 'hard-cheese', 'g', 'fridge'),
  ('Sbrinz', 'sbrinz', 'hard-cheese', 'g', 'fridge'),
  ('Tilsiter', 'tilsiter', 'hard-cheese', 'g', 'fridge'),
  ('Buttermilch', 'buttermilch', 'milk-cream', 'ml', 'fridge'),
  ('Crème fraîche', 'creme fraiche', 'milk-cream', 'g', 'fridge'),
  ('Haferdrink', 'haferdrink', 'milk-cream', 'ml', 'pantry'),
  ('Halbrahm', 'halbrahm', 'milk-cream', 'ml', 'fridge'),
  ('Kaffeerahm', 'kaffeerahm', 'milk-cream', 'ml', 'pantry'),
  ('Kondensmilch', 'kondensmilch', 'milk-cream', 'g', 'pantry'),
  ('Milchdrink', 'milchdrink', 'milk-cream', 'ml', 'fridge'),
  ('Sauerrahm', 'sauerrahm', 'milk-cream', 'g', 'fridge'),
  ('UHT-Vollmilch', 'uht vollmilch', 'milk-cream', 'ml', 'pantry'),
  ('Vollmilch', 'vollmilch', 'milk-cream', 'ml', 'fridge'),
  ('Vollrahm', 'vollrahm', 'milk-cream', 'ml', 'fridge'),
  ('Balsamico', 'balsamico', 'oils-vinegar', 'ml', 'pantry'),
  ('Olivenöl', 'olivenoel', 'oils-vinegar', 'ml', 'pantry'),
  ('Rapsöl', 'rapsoel', 'oils-vinegar', 'ml', 'pantry'),
  ('Sonnenblumenöl', 'sonnenblumenoel', 'oils-vinegar', 'ml', 'pantry'),
  ('Weissweinessig', 'weissweinessig', 'oils-vinegar', 'ml', 'pantry'),
  ('Cornflakes', 'cornflakes', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Frische Lasagneblätter', 'frische lasagneblaetter', 'pasta-rice-cereals', 'piece', 'fridge'),
  ('Frische Ravioli', 'frische ravioli', 'pasta-rice-cereals', 'piece', 'fridge'),
  ('Frische Tagliatelle', 'frische tagliatelle', 'pasta-rice-cereals', 'piece', 'fridge'),
  ('Frische Tortellini', 'frische tortellini', 'pasta-rice-cereals', 'piece', 'fridge'),
  ('Gnocchi', 'gnocchi', 'pasta-rice-cereals', 'piece', 'fridge'),
  ('Haferflocken', 'haferflocken', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Hörnli', 'hoernli', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Langkornreis', 'langkornreis', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Linsen', 'linsen', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Müesli', 'muesli', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Penne', 'penne', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Polenta', 'polenta', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Risottoreis', 'risottoreis', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Spätzli', 'spaetzli', 'pasta-rice-cereals', 'piece', 'fridge'),
  ('Spaghetti', 'spaghetti', 'pasta-rice-cereals', 'g', 'pantry'),
  ('Ingwer', 'ingwer', 'potatoes-root-vegetables', 'g', 'fridge'),
  ('Kartoffeln festkochend', 'kartoffeln festkochend', 'potatoes-root-vegetables', 'g', 'pantry'),
  ('Kartoffeln mehligkochend', 'kartoffeln mehligkochend', 'potatoes-root-vegetables', 'g', 'pantry'),
  ('Knoblauch', 'knoblauch', 'potatoes-root-vegetables', 'piece', 'pantry'),
  ('Kürbis', 'kuerbis', 'potatoes-root-vegetables', 'piece', 'pantry'),
  ('Randen / Rote Bete', 'randen rote bete', 'potatoes-root-vegetables', 'g', 'fridge'),
  ('Rotkabis', 'rotkabis', 'potatoes-root-vegetables', 'piece', 'fridge'),
  ('Rüebli / Karotten', 'ruebli karotten', 'potatoes-root-vegetables', 'g', 'fridge'),
  ('Schalotten', 'schalotten', 'potatoes-root-vegetables', 'g', 'pantry'),
  ('Sellerieknolle', 'sellerieknolle', 'potatoes-root-vegetables', 'piece', 'fridge'),
  ('Süsskartoffeln', 'suesskartoffeln', 'potatoes-root-vegetables', 'g', 'pantry'),
  ('Weisskabis', 'weisskabis', 'potatoes-root-vegetables', 'piece', 'fridge'),
  ('Zwiebeln', 'zwiebeln', 'potatoes-root-vegetables', 'g', 'pantry'),
  ('Basilikum', 'basilikum', 'salad-herbs', 'piece', 'pantry'),
  ('Eisbergsalat', 'eisbergsalat', 'salad-herbs', 'piece', 'fridge'),
  ('Kopfsalat', 'kopfsalat', 'salad-herbs', 'piece', 'fridge'),
  ('Nüsslisalat', 'nuesslisalat', 'salad-herbs', 'g', 'fridge'),
  ('Petersilie', 'petersilie', 'salad-herbs', 'piece', 'fridge'),
  ('Rucola', 'rucola', 'salad-herbs', 'g', 'fridge'),
  ('Salatmischung', 'salatmischung', 'salad-herbs', 'piece', 'fridge'),
  ('Schnittlauch', 'schnittlauch', 'salad-herbs', 'piece', 'fridge'),
  ('Ketchup', 'ketchup', 'sauces-condiments', 'ml', 'pantry'),
  ('Mayonnaise', 'mayonnaise', 'sauces-condiments', 'g', 'pantry'),
  ('Pesto frisch', 'pesto frisch', 'sauces-condiments', 'piece', 'fridge'),
  ('Salatsauce', 'salatsauce', 'sauces-condiments', 'ml', 'pantry'),
  ('Senf', 'senf', 'sauces-condiments', 'g', 'pantry'),
  ('Sojasauce', 'sojasauce', 'sauces-condiments', 'ml', 'pantry'),
  ('Tomatensauce', 'tomatensauce', 'sauces-condiments', 'g', 'pantry'),
  ('Bratwurst', 'bratwurst', 'sausages-cold-cuts', 'piece', 'fridge'),
  ('Cervelat', 'cervelat', 'sausages-cold-cuts', 'piece', 'fridge'),
  ('Fleischkäse', 'fleischkaese', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Mortadella', 'mortadella', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Rohschinken', 'rohschinken', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Salami', 'salami', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Schinken', 'schinken', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Schüblig', 'schueblig', 'sausages-cold-cuts', 'piece', 'fridge'),
  ('Speckwürfeli', 'speckwuerfeli', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Trockenfleisch', 'trockenfleisch', 'sausages-cold-cuts', 'g', 'fridge'),
  ('Wienerli', 'wienerli', 'sausages-cold-cuts', 'piece', 'fridge'),
  ('Brie', 'brie', 'soft-cheese', 'g', 'fridge'),
  ('Camembert', 'camembert', 'soft-cheese', 'g', 'fridge'),
  ('Feta', 'feta', 'soft-cheese', 'g', 'fridge'),
  ('Frischkäse', 'frischkaese', 'soft-cheese', 'g', 'fridge'),
  ('Halloumi', 'halloumi', 'soft-cheese', 'g', 'fridge'),
  ('Hüttenkäse', 'huettenkaese', 'soft-cheese', 'g', 'fridge'),
  ('Mascarpone', 'mascarpone', 'soft-cheese', 'g', 'fridge'),
  ('Mozzarella', 'mozzarella', 'soft-cheese', 'g', 'fridge'),
  ('Ricotta', 'ricotta', 'soft-cheese', 'g', 'fridge'),
  ('Gemüsebouillon', 'gemuesebouillon', 'spices-broth', 'g', 'pantry'),
  ('Oregano getrocknet', 'oregano getrocknet', 'spices-broth', 'g', 'pantry'),
  ('Paprikapulver', 'paprikapulver', 'spices-broth', 'g', 'pantry'),
  ('Pfeffer', 'pfeffer', 'spices-broth', 'g', 'pantry'),
  ('Salz', 'salz', 'spices-broth', 'g', 'pantry'),
  ('Zimt', 'zimt', 'spices-broth', 'g', 'pantry'),
  ('Ahornsirup', 'ahornsirup', 'sweet-spreads', 'ml', 'pantry'),
  ('Erdnussbutter', 'erdnussbutter', 'sweet-spreads', 'g', 'pantry'),
  ('Honig', 'honig', 'sweet-spreads', 'g', 'pantry'),
  ('Konfitüre', 'konfituere', 'sweet-spreads', 'g', 'pantry'),
  ('Schokoladenaufstrich', 'schokoladenaufstrich', 'sweet-spreads', 'g', 'pantry'),
  ('Baumnüsse', 'baumnuesse', 'sweets-snacks', 'g', 'pantry'),
  ('Biscuits', 'biscuits', 'sweets-snacks', 'piece', 'pantry'),
  ('Cashewkerne', 'cashewkerne', 'sweets-snacks', 'g', 'pantry'),
  ('Chips', 'chips', 'sweets-snacks', 'piece', 'pantry'),
  ('Erdnüsse', 'erdnuesse', 'sweets-snacks', 'g', 'pantry'),
  ('Gummibärli', 'gummibaerli', 'sweets-snacks', 'g', 'pantry'),
  ('Mandeln', 'mandeln', 'sweets-snacks', 'g', 'pantry'),
  ('Müesliriegel', 'mueesliriegel', 'sweets-snacks', 'piece', 'pantry'),
  ('Salzstangen', 'salzstangen', 'sweets-snacks', 'g', 'pantry'),
  ('Schokolade', 'schokolade', 'sweets-snacks', 'piece', 'pantry'),
  ('Schokoriegel', 'schokoriegel', 'sweets-snacks', 'piece', 'pantry'),
  ('Studentenfutter', 'studentenfutter', 'sweets-snacks', 'g', 'pantry'),
  ('Fruchtjoghurt', 'fruchtjoghurt', 'yogurt-quark', 'g', 'fridge'),
  ('Griechisches Joghurt', 'griechisches joghurt', 'yogurt-quark', 'g', 'fridge'),
  ('Joghurt nature', 'joghurt nature', 'yogurt-quark', 'g', 'fridge'),
  ('Kefir', 'kefir', 'yogurt-quark', 'ml', 'fridge'),
  ('Kräuterquark', 'kraeuterquark', 'yogurt-quark', 'g', 'fridge'),
  ('Magerquark', 'magerquark', 'yogurt-quark', 'g', 'fridge'),
  ('Skyr', 'skyr', 'yogurt-quark', 'g', 'fridge'),
  ('Trinkjoghurt', 'trinkjoghurt', 'yogurt-quark', 'ml', 'fridge')
) as v(name, normalized_name, category_slug, default_unit, default_storage)
join public.categories c on c.slug = v.category_slug
on conflict (normalized_name) where household_id is null do update
  set name            = excluded.name,
      category_id     = excluded.category_id,
      default_unit    = excluded.default_unit,
      default_storage = excluded.default_storage,
      source          = 'seed',
      verified        = true,
      updated_at      = now();

-- 2b. Verwaiste Startkatalog-Eintraege entfernen -----------------------
--
-- NOETIG, weil der Abgleich oben ueber normalized_name laeuft: Wird genau
-- dieses Feld geaendert (etwa "apfel" zu "apfel aepfel", damit die
-- Mehrzahlform auch trifft), kollidiert nichts — es entsteht eine ZWEITE
-- Zeile, und die alte bleibt stehen. Genau das ist beim ersten Lauf
-- passiert und hat "Apfel" und "Zopf" verdoppelt.
--
-- Entfernt wird ausschliesslich, was aus dem Startkatalog stammt und dort
-- nicht mehr vorkommt. Haushaltseigene Produkte (source='user'),
-- KI-Ergaenzungen ('ai') und uebernommene Fremddaten ('off') bleiben
-- unberuehrt.
--
-- Gefahrlos, weil inventory_items.product_id und intake_lines.product_id
-- auf ON DELETE SET NULL stehen: Ein entfernter Katalogeintrag loescht
-- niemandem den Vorrat, er loest nur die Verknuepfung. Der Artikel behaelt
-- seinen Namen, weil display_name ein Schnappschuss ist (Konzept 5.3).

delete from public.products p
 where p.household_id is null
   and p.source = 'seed'
   and not exists (
     select 1 from (values
       ('apfelsaft'),
       ('bier'),
       ('cola'),
       ('eistee'),
       ('mineralwasser mit kohlensaeure'),
       ('mineralwasser ohne kohlensaeure'),
       ('orangensaft'),
       ('rotwein'),
       ('sirup'),
       ('weisswein'),
       ('baguette'),
       ('bauernbrot'),
       ('buerli'),
       ('burgerbroetchen'),
       ('ciabatta'),
       ('dinkelbrot'),
       ('fladenbrot'),
       ('gipfeli'),
       ('halbweissbrot'),
       ('knaeckebrot'),
       ('laugenbrezel'),
       ('marmorcake'),
       ('muffin'),
       ('nussgipfel'),
       ('pitabrot'),
       ('ruchbrot'),
       ('sauerteigbrot'),
       ('toastbrot'),
       ('tortilla wraps'),
       ('vollkornbrot'),
       ('vollkorntoastbrot'),
       ('weggli'),
       ('weissbrot'),
       ('zopf zoepfe'),
       ('zwieback'),
       ('bratbutter'),
       ('butter'),
       ('margarine'),
       ('streichbutter'),
       ('essiggurken'),
       ('kichererbsen'),
       ('kidneybohnen'),
       ('mais aus der dose'),
       ('pelati'),
       ('thon in der dose'),
       ('tomatenpueree'),
       ('falafel'),
       ('guacamole'),
       ('hummus'),
       ('kuchenteig'),
       ('pflanzliches hackfleisch'),
       ('pizzateig'),
       ('raeuchertofu'),
       ('rauchtofu'),
       ('tofu'),
       ('tofu natur'),
       ('veganes geschnetzeltes'),
       ('vegi bratwurst'),
       ('vegi burger'),
       ('gemahlener kaffee'),
       ('kaffeebohnen'),
       ('kaffeekapseln'),
       ('kraeutertee'),
       ('schwarztee'),
       ('eier'),
       ('gekochte eier'),
       ('crevetten'),
       ('eglifilet'),
       ('forellenfilet'),
       ('kabeljaufilet'),
       ('lachsfilet'),
       ('miesmuscheln'),
       ('raeucherlachs'),
       ('surimi'),
       ('backpulver'),
       ('blaetterteig'),
       ('frischhefe'),
       ('gemahlene haselnuesse'),
       ('kakaopulver'),
       ('maisstaerke'),
       ('puderzucker'),
       ('rosinen'),
       ('ruchmehl'),
       ('trockenhefe'),
       ('vanillezucker'),
       ('weissmehl'),
       ('zopfmehl'),
       ('zucker'),
       ('ananas'),
       ('apfel aepfel'),
       ('aprikosen'),
       ('avocado'),
       ('banane'),
       ('birne'),
       ('brombeeren'),
       ('erdbeeren'),
       ('heidelbeeren'),
       ('himbeeren'),
       ('honigmelone'),
       ('kiwi'),
       ('mandarine'),
       ('nektarine'),
       ('orange'),
       ('pfirsich'),
       ('wassermelone'),
       ('weintrauben'),
       ('zitrone'),
       ('zwetschgen'),
       ('entrecote'),
       ('ganzes poulet'),
       ('hackfleisch gemischt'),
       ('hacktaetschli'),
       ('kalbsschnitzel'),
       ('lammkoteletts'),
       ('poulet geschnetzeltes'),
       ('pouletbrust'),
       ('pouletschenkel'),
       ('rindsfilet'),
       ('rindshackfleisch'),
       ('rindsplaetzli'),
       ('rindsvoressen'),
       ('schweinsfilet'),
       ('schweinskotelett'),
       ('schweinsschnitzel'),
       ('trutenbrust'),
       ('aubergine'),
       ('blumenkohl'),
       ('broccoli'),
       ('champignons'),
       ('cherrytomaten'),
       ('fenchel'),
       ('fruehlingszwiebeln'),
       ('gruene bohnen'),
       ('gurke'),
       ('kohlrabi'),
       ('lauch'),
       ('peperoni'),
       ('spinat'),
       ('stangensellerie'),
       ('tomaten'),
       ('zucchetti'),
       ('chicken nuggets'),
       ('fischstaebchen'),
       ('glace'),
       ('pommes frites'),
       ('tiefkuehl gipfeli'),
       ('tiefkuehlbeeren'),
       ('tiefkuehlerbsen'),
       ('tiefkuehlgemuese mischung'),
       ('tiefkuehllasagne'),
       ('tiefkuehlpizza'),
       ('tiefkuehlspinat'),
       ('appenzeller'),
       ('emmentaler'),
       ('fondue mischung'),
       ('gruyere'),
       ('kaesescheiben'),
       ('parmesan'),
       ('raclettekaese'),
       ('reibkaese'),
       ('sbrinz'),
       ('tilsiter'),
       ('buttermilch'),
       ('creme fraiche'),
       ('haferdrink'),
       ('halbrahm'),
       ('kaffeerahm'),
       ('kondensmilch'),
       ('milchdrink'),
       ('sauerrahm'),
       ('uht vollmilch'),
       ('vollmilch'),
       ('vollrahm'),
       ('balsamico'),
       ('olivenoel'),
       ('rapsoel'),
       ('sonnenblumenoel'),
       ('weissweinessig'),
       ('cornflakes'),
       ('frische lasagneblaetter'),
       ('frische ravioli'),
       ('frische tagliatelle'),
       ('frische tortellini'),
       ('gnocchi'),
       ('haferflocken'),
       ('hoernli'),
       ('langkornreis'),
       ('linsen'),
       ('muesli'),
       ('penne'),
       ('polenta'),
       ('risottoreis'),
       ('spaetzli'),
       ('spaghetti'),
       ('ingwer'),
       ('kartoffeln festkochend'),
       ('kartoffeln mehligkochend'),
       ('knoblauch'),
       ('kuerbis'),
       ('randen rote bete'),
       ('rotkabis'),
       ('ruebli karotten'),
       ('schalotten'),
       ('sellerieknolle'),
       ('suesskartoffeln'),
       ('weisskabis'),
       ('zwiebeln'),
       ('basilikum'),
       ('eisbergsalat'),
       ('kopfsalat'),
       ('nuesslisalat'),
       ('petersilie'),
       ('rucola'),
       ('salatmischung'),
       ('schnittlauch'),
       ('ketchup'),
       ('mayonnaise'),
       ('pesto frisch'),
       ('salatsauce'),
       ('senf'),
       ('sojasauce'),
       ('tomatensauce'),
       ('bratwurst'),
       ('cervelat'),
       ('fleischkaese'),
       ('mortadella'),
       ('rohschinken'),
       ('salami'),
       ('schinken'),
       ('schueblig'),
       ('speckwuerfeli'),
       ('trockenfleisch'),
       ('wienerli'),
       ('brie'),
       ('camembert'),
       ('feta'),
       ('frischkaese'),
       ('halloumi'),
       ('huettenkaese'),
       ('mascarpone'),
       ('mozzarella'),
       ('ricotta'),
       ('gemuesebouillon'),
       ('oregano getrocknet'),
       ('paprikapulver'),
       ('pfeffer'),
       ('salz'),
       ('zimt'),
       ('ahornsirup'),
       ('erdnussbutter'),
       ('honig'),
       ('konfituere'),
       ('schokoladenaufstrich'),
       ('baumnuesse'),
       ('biscuits'),
       ('cashewkerne'),
       ('chips'),
       ('erdnuesse'),
       ('gummibaerli'),
       ('mandeln'),
       ('mueesliriegel'),
       ('salzstangen'),
       ('schokolade'),
       ('schokoriegel'),
       ('studentenfutter'),
       ('fruchtjoghurt'),
       ('griechisches joghurt'),
       ('joghurt nature'),
       ('kefir'),
       ('kraeuterquark'),
       ('magerquark'),
       ('skyr'),
       ('trinkjoghurt')
     ) as gewollt(normalized_name)
      where gewollt.normalized_name = p.normalized_name
   );

-- 3. Haltbarkeitsregeln ------------------------------------------------

delete from public.shelf_life_rules
 where source = 'seed' and household_id is null;

-- 3a. Kategorieregeln: das Auffangnetz fuer alles, was der Katalog nicht kennt.

insert into public.shelf_life_rules
  (scope, category_id, storage, days_unopened, days_opened, household_id, source)
select 'category', c.id, v.storage, v.days_unopened, v.days_opened, null, 'seed'
from (values
  ('fresh-fruit', 'pantry', 4, 2),
  ('fresh-fruit', 'fridge', 7, 2),
  ('fresh-fruit', 'freezer', 180, null),
  ('fresh-vegetables', 'pantry', 4, 3),
  ('fresh-vegetables', 'fridge', 7, 3),
  ('fresh-vegetables', 'freezer', 180, null),
  ('salad-herbs', 'pantry', 2, 2),
  ('salad-herbs', 'fridge', 4, 2),
  ('potatoes-root-vegetables', 'pantry', 21, 3),
  ('potatoes-root-vegetables', 'fridge', 30, 3),
  ('milk-cream', 'pantry', 90, 3),
  ('milk-cream', 'fridge', 7, 3),
  ('yogurt-quark', 'fridge', 14, 3),
  ('hard-cheese', 'fridge', 30, 14),
  ('hard-cheese', 'freezer', 90, null),
  ('soft-cheese', 'fridge', 12, 3),
  ('butter-fats', 'fridge', 45, 21),
  ('butter-fats', 'freezer', 180, null),
  ('eggs', 'pantry', 12, null),
  ('eggs', 'fridge', 21, null),
  ('fresh-meat', 'fridge', 2, 1),
  ('fresh-meat', 'freezer', 120, null),
  ('sausages-cold-cuts', 'fridge', 14, 3),
  ('sausages-cold-cuts', 'freezer', 60, null),
  ('fish-seafood', 'fridge', 1, 1),
  ('fish-seafood', 'freezer', 90, null),
  ('chilled-convenience', 'fridge', 8, 3),
  ('chilled-convenience', 'freezer', 60, null),
  ('frozen-food', 'fridge', 1, 90),
  ('frozen-food', 'freezer', 270, null),
  ('bread-bakery', 'pantry', 3, 2),
  ('bread-bakery', 'fridge', 6, 2),
  ('bread-bakery', 'freezer', 90, null),
  ('pasta-rice-cereals', 'pantry', 365, 90),
  ('flour-baking', 'pantry', 270, 120),
  ('canned-jarred', 'pantry', 730, 3),
  ('sauces-condiments', 'pantry', 365, 28),
  ('sauces-condiments', 'fridge', 365, 28),
  ('oils-vinegar', 'pantry', 365, 180),
  ('spices-broth', 'pantry', 730, 365),
  ('sweet-spreads', 'pantry', 365, 30),
  ('sweet-spreads', 'fridge', 365, 30),
  ('sweets-snacks', 'pantry', 180, 14),
  ('coffee-tea', 'pantry', 365, 60),
  ('beverages', 'pantry', 365, 4),
  ('beverages', 'fridge', 90, 4)
) as v(category_slug, storage, days_unopened, days_opened)
join public.categories c on c.slug = v.category_slug;

-- 3b. Produktregeln: genauer als die Kategorie und deshalb vorrangig.

insert into public.shelf_life_rules
  (scope, product_id, storage, days_unopened, days_opened, household_id, source)
select 'product', p.id, v.storage, v.days_unopened, v.days_opened, null, 'seed'
from (values
  ('apfelsaft', 'pantry', 270, 5),
  ('bier', 'pantry', 180, 1),
  ('cola', 'pantry', 270, 3),
  ('eistee', 'pantry', 270, 3),
  ('mineralwasser mit kohlensaeure', 'pantry', 365, 5),
  ('mineralwasser ohne kohlensaeure', 'pantry', 365, 3),
  ('orangensaft', 'pantry', 180, 4),
  ('rotwein', 'pantry', 1095, 3),
  ('sirup', 'pantry', 365, 45),
  ('weisswein', 'pantry', 730, 3),
  ('baguette', 'pantry', 1, null),
  ('bauernbrot', 'pantry', 4, null),
  ('buerli', 'pantry', 2, null),
  ('burgerbroetchen', 'pantry', 10, 4),
  ('ciabatta', 'pantry', 2, null),
  ('dinkelbrot', 'pantry', 4, null),
  ('fladenbrot', 'pantry', 3, 2),
  ('gipfeli', 'pantry', 2, null),
  ('halbweissbrot', 'pantry', 3, null),
  ('knaeckebrot', 'pantry', 180, 30),
  ('laugenbrezel', 'pantry', 2, null),
  ('marmorcake', 'pantry', 21, 7),
  ('muffin', 'pantry', 5, null),
  ('nussgipfel', 'pantry', 2, null),
  ('pitabrot', 'pantry', 7, 3),
  ('ruchbrot', 'pantry', 3, null),
  ('sauerteigbrot', 'pantry', 5, null),
  ('toastbrot', 'pantry', 10, 6),
  ('tortilla wraps', 'pantry', 60, 5),
  ('vollkornbrot', 'pantry', 4, null),
  ('vollkorntoastbrot', 'pantry', 8, 5),
  ('weggli', 'pantry', 2, null),
  ('weissbrot', 'pantry', 2, null),
  ('zopf zoepfe', 'pantry', 3, null),
  ('zwieback', 'pantry', 180, 30),
  ('bratbutter', 'fridge', 90, 45),
  ('butter', 'fridge', 30, 14),
  ('margarine', 'fridge', 45, 21),
  ('streichbutter', 'fridge', 30, 14),
  ('essiggurken', 'pantry', 540, 60),
  ('kichererbsen', 'pantry', 730, 3),
  ('kidneybohnen', 'pantry', 730, 3),
  ('mais aus der dose', 'pantry', 730, 3),
  ('pelati', 'pantry', 730, 3),
  ('thon in der dose', 'pantry', 730, 1),
  ('tomatenpueree', 'pantry', 730, 7),
  ('falafel', 'fridge', 10, 3),
  ('guacamole', 'fridge', 14, 2),
  ('hummus', 'fridge', 21, 3),
  ('kuchenteig', 'fridge', 21, 2),
  ('pflanzliches hackfleisch', 'fridge', 10, 2),
  ('pizzateig', 'fridge', 14, 2),
  ('raeuchertofu', 'fridge', 30, 3),
  ('rauchtofu', 'fridge', 21, 3),
  ('tofu', 'fridge', 21, 3),
  ('tofu natur', 'fridge', 21, 3),
  ('veganes geschnetzeltes', 'fridge', 14, 2),
  ('vegi bratwurst', 'fridge', 14, 2),
  ('vegi burger', 'fridge', 14, 2),
  ('gemahlener kaffee', 'pantry', 365, 14),
  ('kaffeebohnen', 'pantry', 365, 21),
  ('kaffeekapseln', 'pantry', 365, null),
  ('kraeutertee', 'pantry', 540, 270),
  ('schwarztee', 'pantry', 540, 270),
  ('eier', 'fridge', 21, null),
  ('gekochte eier', 'fridge', 14, null),
  ('crevetten', 'fridge', 2, 1),
  ('eglifilet', 'fridge', 1, 1),
  ('forellenfilet', 'fridge', 2, 1),
  ('kabeljaufilet', 'fridge', 2, 1),
  ('lachsfilet', 'fridge', 2, 1),
  ('miesmuscheln', 'fridge', 1, null),
  ('raeucherlachs', 'fridge', 14, 2),
  ('surimi', 'fridge', 14, 2),
  ('backpulver', 'pantry', 540, 90),
  ('blaetterteig', 'fridge', 21, 2),
  ('frischhefe', 'fridge', 14, 2),
  ('gemahlene haselnuesse', 'pantry', 120, 30),
  ('kakaopulver', 'pantry', 540, 180),
  ('maisstaerke', 'pantry', 730, 365),
  ('puderzucker', 'pantry', 540, 180),
  ('rosinen', 'pantry', 270, 60),
  ('ruchmehl', 'pantry', 270, 90),
  ('trockenhefe', 'pantry', 365, 90),
  ('vanillezucker', 'pantry', 540, 90),
  ('weissmehl', 'pantry', 365, 180),
  ('zopfmehl', 'pantry', 365, 180),
  ('zucker', 'pantry', 1095, 730),
  ('ananas', 'pantry', 4, 3),
  ('apfel aepfel', 'pantry', 14, null),
  ('aprikosen', 'fridge', 4, null),
  ('avocado', 'pantry', 4, 1),
  ('banane', 'pantry', 5, null),
  ('birne', 'pantry', 5, null),
  ('brombeeren', 'fridge', 2, null),
  ('erdbeeren', 'fridge', 2, null),
  ('heidelbeeren', 'fridge', 5, null),
  ('himbeeren', 'fridge', 2, null),
  ('honigmelone', 'fridge', 6, 2),
  ('kiwi', 'pantry', 8, null),
  ('mandarine', 'pantry', 8, null),
  ('nektarine', 'fridge', 4, null),
  ('orange', 'pantry', 10, null),
  ('pfirsich', 'fridge', 4, null),
  ('wassermelone', 'fridge', 7, 2),
  ('weintrauben', 'fridge', 6, null),
  ('zitrone', 'pantry', 14, 2),
  ('zwetschgen', 'fridge', 5, null),
  ('entrecote', 'fridge', 3, 1),
  ('ganzes poulet', 'fridge', 2, 1),
  ('hackfleisch gemischt', 'fridge', 1, 1),
  ('hacktaetschli', 'fridge', 1, 1),
  ('kalbsschnitzel', 'fridge', 2, 1),
  ('lammkoteletts', 'fridge', 2, 1),
  ('poulet geschnetzeltes', 'fridge', 1, 1),
  ('pouletbrust', 'fridge', 2, 1),
  ('pouletschenkel', 'fridge', 2, 1),
  ('rindsfilet', 'fridge', 3, 1),
  ('rindshackfleisch', 'fridge', 1, 1),
  ('rindsplaetzli', 'fridge', 2, 1),
  ('rindsvoressen', 'fridge', 2, 1),
  ('schweinsfilet', 'fridge', 2, 1),
  ('schweinskotelett', 'fridge', 2, 1),
  ('schweinsschnitzel', 'fridge', 2, 1),
  ('trutenbrust', 'fridge', 2, 1),
  ('aubergine', 'fridge', 5, null),
  ('blumenkohl', 'fridge', 5, null),
  ('broccoli', 'fridge', 4, null),
  ('champignons', 'fridge', 4, 3),
  ('cherrytomaten', 'pantry', 6, null),
  ('fenchel', 'fridge', 7, null),
  ('fruehlingszwiebeln', 'fridge', 6, null),
  ('gruene bohnen', 'fridge', 4, null),
  ('gurke', 'fridge', 7, 3),
  ('kohlrabi', 'fridge', 7, null),
  ('lauch', 'fridge', 8, null),
  ('peperoni', 'fridge', 7, 3),
  ('spinat', 'fridge', 3, null),
  ('stangensellerie', 'fridge', 7, null),
  ('tomaten', 'pantry', 6, null),
  ('zucchetti', 'fridge', 7, null),
  ('chicken nuggets', 'freezer', 270, 60),
  ('fischstaebchen', 'freezer', 270, 60),
  ('glace', 'freezer', 365, 30),
  ('pommes frites', 'freezer', 365, 90),
  ('tiefkuehl gipfeli', 'freezer', 180, 90),
  ('tiefkuehlbeeren', 'freezer', 270, 60),
  ('tiefkuehlerbsen', 'freezer', 365, 90),
  ('tiefkuehlgemuese mischung', 'freezer', 365, 90),
  ('tiefkuehllasagne', 'freezer', 270, null),
  ('tiefkuehlpizza', 'freezer', 270, null),
  ('tiefkuehlspinat', 'freezer', 365, 90),
  ('appenzeller', 'fridge', 21, 8),
  ('emmentaler', 'fridge', 21, 10),
  ('fondue mischung', 'fridge', 21, 2),
  ('gruyere', 'fridge', 21, 10),
  ('kaesescheiben', 'fridge', 21, 5),
  ('parmesan', 'fridge', 45, 21),
  ('raclettekaese', 'fridge', 18, 7),
  ('reibkaese', 'fridge', 21, 5),
  ('sbrinz', 'fridge', 45, 21),
  ('tilsiter', 'fridge', 18, 8),
  ('buttermilch', 'fridge', 7, 3),
  ('creme fraiche', 'fridge', 14, 5),
  ('haferdrink', 'pantry', 150, 4),
  ('halbrahm', 'fridge', 14, 3),
  ('kaffeerahm', 'pantry', 90, 3),
  ('kondensmilch', 'pantry', 270, 7),
  ('milchdrink', 'fridge', 6, 3),
  ('sauerrahm', 'fridge', 14, 4),
  ('uht vollmilch', 'pantry', 120, 3),
  ('vollmilch', 'fridge', 6, 3),
  ('vollrahm', 'fridge', 10, 3),
  ('balsamico', 'pantry', 1095, 730),
  ('olivenoel', 'pantry', 540, 180),
  ('rapsoel', 'pantry', 365, 120),
  ('sonnenblumenoel', 'pantry', 365, 180),
  ('weissweinessig', 'pantry', 1095, 730),
  ('cornflakes', 'pantry', 270, 30),
  ('frische lasagneblaetter', 'fridge', 14, 3),
  ('frische ravioli', 'fridge', 10, 2),
  ('frische tagliatelle', 'fridge', 14, 2),
  ('frische tortellini', 'fridge', 10, 2),
  ('gnocchi', 'fridge', 21, 2),
  ('haferflocken', 'pantry', 365, 120),
  ('hoernli', 'pantry', 730, 180),
  ('langkornreis', 'pantry', 730, 365),
  ('linsen', 'pantry', 540, 365),
  ('muesli', 'pantry', 300, 60),
  ('penne', 'pantry', 730, 180),
  ('polenta', 'pantry', 365, 180),
  ('risottoreis', 'pantry', 730, 365),
  ('spaetzli', 'fridge', 14, 2),
  ('spaghetti', 'pantry', 730, 180),
  ('ingwer', 'fridge', 21, null),
  ('kartoffeln festkochend', 'pantry', 21, null),
  ('kartoffeln mehligkochend', 'pantry', 21, null),
  ('knoblauch', 'pantry', 45, null),
  ('kuerbis', 'pantry', 30, 7),
  ('randen rote bete', 'fridge', 21, null),
  ('rotkabis', 'fridge', 30, 7),
  ('ruebli karotten', 'fridge', 21, null),
  ('schalotten', 'pantry', 30, null),
  ('sellerieknolle', 'fridge', 21, null),
  ('suesskartoffeln', 'pantry', 21, null),
  ('weisskabis', 'fridge', 30, 7),
  ('zwiebeln', 'pantry', 30, null),
  ('basilikum', 'pantry', 10, null),
  ('eisbergsalat', 'fridge', 7, null),
  ('kopfsalat', 'fridge', 4, null),
  ('nuesslisalat', 'fridge', 3, 2),
  ('petersilie', 'fridge', 5, null),
  ('rucola', 'fridge', 3, 2),
  ('salatmischung', 'fridge', 3, 1),
  ('schnittlauch', 'fridge', 5, null),
  ('ketchup', 'pantry', 540, 56),
  ('mayonnaise', 'pantry', 365, 28),
  ('pesto frisch', 'fridge', 21, 4),
  ('salatsauce', 'pantry', 365, 45),
  ('senf', 'pantry', 540, 90),
  ('sojasauce', 'pantry', 730, 180),
  ('tomatensauce', 'pantry', 540, 4),
  ('bratwurst', 'fridge', 2, 1),
  ('cervelat', 'fridge', 7, 3),
  ('fleischkaese', 'fridge', 5, 2),
  ('mortadella', 'fridge', 14, 3),
  ('rohschinken', 'fridge', 21, 4),
  ('salami', 'fridge', 21, 4),
  ('schinken', 'fridge', 14, 3),
  ('schueblig', 'fridge', 7, 3),
  ('speckwuerfeli', 'fridge', 21, 3),
  ('trockenfleisch', 'fridge', 30, 5),
  ('wienerli', 'fridge', 10, 3),
  ('brie', 'fridge', 14, 3),
  ('camembert', 'fridge', 14, 3),
  ('feta', 'fridge', 30, 7),
  ('frischkaese', 'fridge', 21, 7),
  ('halloumi', 'fridge', 45, 5),
  ('huettenkaese', 'fridge', 14, 3),
  ('mascarpone', 'fridge', 14, 3),
  ('mozzarella', 'fridge', 14, 2),
  ('ricotta', 'fridge', 10, 2),
  ('gemuesebouillon', 'pantry', 540, 180),
  ('oregano getrocknet', 'pantry', 540, 180),
  ('paprikapulver', 'pantry', 540, 180),
  ('pfeffer', 'pantry', 730, 365),
  ('salz', 'pantry', 1825, 1825),
  ('zimt', 'pantry', 540, 365),
  ('ahornsirup', 'pantry', 730, 180),
  ('erdnussbutter', 'pantry', 365, 90),
  ('honig', 'pantry', 1095, 730),
  ('konfituere', 'pantry', 540, 30),
  ('schokoladenaufstrich', 'pantry', 365, 90),
  ('baumnuesse', 'pantry', 150, 30),
  ('biscuits', 'pantry', 180, 14),
  ('cashewkerne', 'pantry', 180, 45),
  ('chips', 'pantry', 90, 2),
  ('erdnuesse', 'pantry', 180, 21),
  ('gummibaerli', 'pantry', 270, 30),
  ('mandeln', 'pantry', 240, 60),
  ('mueesliriegel', 'pantry', 180, null),
  ('salzstangen', 'pantry', 180, 7),
  ('schokolade', 'pantry', 365, 30),
  ('schokoriegel', 'pantry', 180, null),
  ('studentenfutter', 'pantry', 180, 30),
  ('fruchtjoghurt', 'fridge', 14, 2),
  ('griechisches joghurt', 'fridge', 14, 3),
  ('joghurt nature', 'fridge', 14, 3),
  ('kefir', 'fridge', 12, 4),
  ('kraeuterquark', 'fridge', 10, 3),
  ('magerquark', 'fridge', 14, 3),
  ('skyr', 'fridge', 14, 3),
  ('trinkjoghurt', 'fridge', 14, 2)
) as v(normalized_name, storage, days_unopened, days_opened)
join public.products p
  on p.normalized_name = v.normalized_name
 and p.household_id is null;
